name: spotify_manager
description: A new Flutter application. for managing spotify playlists.

version: 1.0.1+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^1.5.0
  uuid: ^2.0.4
  percent_indicator: ^2.1.1
  http: ^0.12.0+3
  json_annotation: ^3.0.1
  webview_flutter: ^0.3.19+8
  audioplayer: ^0.8.1
  path_provider: ^1.5.1
  marquee: ^1.3.1
  sqflite: ^1.2.1
  smooth_page_indicator: ^0.1.5
  spotify:
    path: ../../spotify-dart

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/mix_app7.png"
  image_path_ios: "assets/mix_app_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
